Passing optional arguments to Comunica
LDflex/LDflex-Comunica pull request #21
Opened 2020-10-19 16:36 UTC by danielbeeke

See https://github.com/LDflex/LDflex/issues/70

2020-10-19 16:41 UTC, RubenVerborgh requested changes

2020-10-19 16:41 UTC, RubenVerborgh commented on src/ComunicaEngine.js
> +  constructor(defaultSource, optionalArguments) {
```suggestion
  constructor(defaultSource, options) {
```

2020-10-19 16:41 UTC, RubenVerborgh commented on src/ComunicaEngine.js
> +    this._optionalArguments = optionalArguments;
```suggestion
    this._options = options;
```

2020-10-19 16:41 UTC, RubenVerborgh commented on src/ComunicaEngine.js
> +      const queryResult = await this._engine.query(sparql, Object.assign({ sources }, this._optionalArguments));
```suggestion
      const queryResult = await this._engine.query(sparql, { sources, ...ths._options });
```

2020-10-19 17:38 UTC, danielbeeke commented
Interesting enough, the options are passed. But I can not get it work. 
I am using it to pass a httpProxyHandler like:

```
        const queryEngine = new ComunicaEngine(uri, {
          'httpProxyHandler': this.form.proxy
        });

        const path = new PathFactory({ context: this.pathContext, queryEngine });
        const object = path.create({ subject: namedNode(uri) })
```

2021-04-14 09:53 UTC, danielbeeke commented
Can be closed in favor of #24 24

2021-04-14 09:53 UTC, closed without merging